// Mocks generated by Mockito 5.4.4 from annotations
// in student_management_starter/test/unit_test/course_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management_starter/core/failure/failure.dart' as _i6;
import 'package:student_management_starter/features/batch/domain/entity/batch_entity.dart'
    as _i8;
import 'package:student_management_starter/features/course/domain/entity/course_entity.dart'
    as _i7;
import 'package:student_management_starter/features/course/domain/repository/course_repository.dart'
    as _i2;
import 'package:student_management_starter/features/course/domain/usecases/course_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeICourseRepository_0 extends _i1.SmartFake
    implements _i2.ICourseRepository {
  _FakeICourseRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseUseCase extends _i1.Mock implements _i4.CourseUseCase {
  @override
  _i2.ICourseRepository get courseRepository => (super.noSuchMethod(
        Invocation.getter(#courseRepository),
        returnValue: _FakeICourseRepository_0(
          this,
          Invocation.getter(#courseRepository),
        ),
        returnValueForMissingStub: _FakeICourseRepository_0(
          this,
          Invocation.getter(#courseRepository),
        ),
      ) as _i2.ICourseRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addCourse(
          _i7.CourseEntity? course) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCourse,
          [course],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addCourse,
            [course],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addCourse,
            [course],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.CourseEntity>>> getAllCourses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCourses,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.CourseEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.CourseEntity>>(
          this,
          Invocation.method(
            #getAllCourses,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.CourseEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.CourseEntity>>(
          this,
          Invocation.method(
            #getAllCourses,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.CourseEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> deleteCourse(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCourse,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteCourse,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteCourse,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.BatchEntity>>> getAllBatches() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBatches,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.BatchEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.BatchEntity>>(
          this,
          Invocation.method(
            #getAllBatches,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.BatchEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.BatchEntity>>(
          this,
          Invocation.method(
            #getAllBatches,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.BatchEntity>>>);
}
